Allow publishing of multiple images on a single call
Depending on how the repository and images correlate, especially on
monorepos, developers should be capable of publishing multiple images
using the same project, tags, etc.

We changed the parameter `-i` from a single string to an array of
strings, thus enabling the use of multiple `-i` parameters. Also, as
we already had a mechanism to load a file named `image.docker` by
default to help with multiple steps on bitbucket, I've extended that
functionality by loading any file named `$image.docker`, following the
image names which the caller wants to publish.

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -7,14 +7,14 @@ function exit_on_error() {
   fi
 }
 
-declare -a tags
+declare -a tags images
 while getopts ":k:i:p:t:" OPT; do
   case "$OPT" in
   k)
     keyfile="$OPTARG"
     ;;
   i)
-    image="$OPTARG"
+    images+=("$OPTARG")
     ;;
   p)
     project="$OPTARG"
@@ -37,29 +37,50 @@ if [ -z "$project" ] || [ -z "$keyfile" ] || [ -z "$image" ]; then
   exit 1
 fi
 
+if [ "${#tags[@]}" -eq 0 ]; then
+  echo "ERRO: Especifique pelo menos uma tag com -t 'tag'"
+  exit 1
+fi
+
+if [ "${#images[@]}" -eq 0 ]; then
+  echo "ERRO: Especifique pelo menos uma imagem com -i 'image'"
+  exit 1
+fi
+
 docker-login "$project" "$keyfile"
 exit_on_error
 
-repository="gcr.io/$project/$image"
-exit_on_error
-
-if [ "${#tags[@]}" -eq 0 ]; then
-  echo "ERRO: Especifique pelo menos uma tag com -t 'tag'"
-fi
-
 if [ -f ./image.docker ]; then
-  docker load --input ./image.docker
+  docker load --input ./image.docker 1> /dev/null
 fi
 
-for tag in "${tags[@]}"; do
-  docker tag "$image" "$repository":"$tag"
-  docker push "$repository":"$tag"
+for image in "${images[@]}"; do
+  if (! docker image inspect "$image" &> /dev/null); then
+    if [ -f "$image.docker" ]; then
+      docker load --input "$image.docker" 1> /dev/null
+    else
+      echo "ERROR: neither image={${image}} nor ${image}.docker file exists"
+      exit 1
+    fi
+  fi
+done
+
+declare -a published
+for image in "${images[@]}"; do
+  repository="gcr.io/$project/$image"
+
+  for tag in "${tags[@]}"; do
+    to_publish="$repository:$tag"
+
+    docker tag "$image" "$to_publish"
+    docker push "$to_publish"
+
+    published+=("$to_publish")
+  done
 done
 
 echo "Imagens publicadas"
-for tag in "${tags[@]}"; do
-  echo "$repository:$tag"
+for image in "${published[@]}"; do
+  echo "$image"
 done
 
-
-exit 0
